{{- if not .Values.config.existingConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
{{- with .Values.config.annotations }}
  annotations:
{{ tpl ( toYaml . ) $ | indent 4 }}
{{- end }}
  labels:
    app: {{ template "oauth2-proxy.name" . }}
{{- include "oauth2-proxy.labels" . | indent 4 }}
  name: {{ template "oauth2-proxy.fullname" . }}
  namespace: {{ template "oauth2-proxy.namespace" $ }}
data:
  {{- if and .Values.config.configFile (or (not .Values.alphaConfig.enabled) .Values.config.forceLegacyConfig) }}
  oauth2_proxy.cfg: {{ tpl .Values.config.configFile $ | quote }}
  {{- else if .Values.alphaConfig.enabled }}
  oauth2_proxy.cfg: {{ printf "email_domains = %s" (.Values.config.emailDomains | toJson) | quote }}
  {{- else }}
  oauth2_proxy.cfg: {{ printf "email_domains = %s\nupstreams = %s" (.Values.config.emailDomains | toJson) (.Values.config.upstreams | toJson) | quote }}
  {{- end }}
{{- end }}
